---
name: Merges

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
env:
  DOCKER_BUILDCONTEXT: '.'
  DOCKER_FILEPATH: 'Dockerfile'
  DOCKER_REPOSITORY: ${{ github.repository }}
  DOCKER_IMAGE: ${{ github.event.repository.name }}


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE }}
          path: ${{ env.DOCKER_BUILDCONTEXT }}
          dockerfile: ${{ env.DOCKER_FILEPATH }}
          tag_with_ref: true

